# Generated by Django 3.2 on 2024-01-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20240118_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='savings_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
